name: Build and push

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Build the image
      run: docker build --target cli --tag ghcr.io/${{ env.REPOSITORY_OWNER_LC }}/arcan-2-cli-trial:latest
    - name: Push the image
      run: docker push ghcr.io/${{ env.REPOSITORY_OWNER_LC }}/arcan-2-cli-trial:latest
